# Generated by Django 4.2.24 on 2025-09-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_done",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда привычка была последний раз выполнена",
                null=True,
                verbose_name="Дата и время последнего выполнения",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="last_missed",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда привычка была последний раз пропущена",
                null=True,
                verbose_name="Дата и время последнего пропуска",
            ),
        ),
    ]
