# Generated by Django 4.2.24 on 2025-09-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habit_last_done_habit_last_missed"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Выполнено"),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="Привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отметка привычки",
                "verbose_name_plural": "Отметки привычек",
                "unique_together": {("habit", "date")},
            },
        ),
    ]
