# Generated by Django 4.2.24 on 2025-09-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "telegram_bot",
            "0003_alter_telegramuser_chat_id_alter_telegramuser_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="habitrecord",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="habitrecord",
            name="habit",
        ),
        migrations.DeleteModel(
            name="Habit",
        ),
        migrations.DeleteModel(
            name="HabitRecord",
        ),
    ]
